FROM archlinux:base

RUN pacman -Syuu --noconfirm git jdk-openjdk libxcrypt-compat wget2-no-docs wget curl android-sdk android-sdk-platform-tools android-sdk-cmdline-tools-latest android-sdk-build-tools
