name: CI

on:
  push:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: 23
          cache: 'gradle'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Cache konan directory
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts', 'buildSrc/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Run benchmarks
        run: ./gradlew benchmarks:benchmark
