name: debugger-windows

on:
  workflow_call:
    outputs:
      debugger:
        value: ${{ jobs.publish.outputs.debugger-url }}
      sample:
        value: ${{ jobs.publish.outputs.sample-url }}

concurrency:
  group: "publish-win"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: windows-latest
    environment: publishing
    outputs:
      debugger-url: ${{ steps.upload-debugger.outputs.artifact-url }}
      sample-url: ${{ steps.upload-sample.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v5

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: 23
          cache: 'gradle'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        shell: bash
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Cache konan directory
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts', 'buildSrc/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Create platform debugger distributable
        run: ./gradlew debugger:app:packageDistributionForCurrentOS

      - name: Create platform sample distributable
        run: ./gradlew sample:packageDistributionForCurrentOS

      - name: Upload debugger
        id: upload-debugger
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Debugger_Windows
          path: ./debugger/app/build/compose/binaries/main/exe/*
          if-no-files-found: error
          compression-level: 0
          overwrite: false

      - name: Upload sample
        id: upload-sample
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Sample_Windows
          path: ./sample/build/compose/binaries/main/exe/*
          if-no-files-found: error
          compression-level: 0
          overwrite: false
